name: Deploy Resources

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-resources:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - uses: azure/actions/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI - Create Data Resources
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az account show
          az sql server create -l westus2 -u rbanick -p ${{ secrets.SQL_CREDENTIALS }} -n ${{ secrets.SQL_SERVER_NAME }} -g ${{ secrets.AZURE_RG }}
          az sql db create -g ${{ secrets.AZURE_RG }} -s ${{ secrets.SQL_SERVER_NAME }} -n ${{ secrets.SQL_DB_NAME }} -e Standard

    - name: ARM Deploy - Create App Service Resoures
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: .github/workflows/app-service-template.json
        
  build-test-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
