name: Deploy Resources

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - uses: azure/actions/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI - Create Data Resources
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az account show
          az sql server create -l westus2 -u rbanick -p ${{ secrets.SQL_CREDENTIALS }} -n banick-rocket-server -g ${{ secrets.AZURE_RG }}

    - name: ARM Deploy - Create App Service Resoures
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: .github/workflows/app-service-template.json
